data_path: './data/score.db'
model: 'linearsvc'
random_seed: 1
test_size: 0.2
shuffle: True
cross_val_num: 5

# Model parameters
lasso__alpha: [1.e-15, 1.e-10, 1.e-8, 1.e-5, 1.e-4, 1.e-3, 1.e-2, 1, 5, 10]
ridge__alpha: [1.e-15, 1.e-10, 1.e-8, 1.e-5, 1.e-4, 1.e-3, 1.e-2, 1, 5, 10]
linearsvc__loss: ['hinge', 'squared_hinge']
linearsvc__C: [1.e-15, 1.e-10, 1.e-8, 1.e-5, 1.e-4, 1.e-3, 1.e-2, 1, 5, 10]
kneighborsclassifier__n_neighbors: [2, 3, 4, 5, 6, 7, 8, 9, 10]
kneighborsclassifier__weights: ['uniform', 'distance']

# Data parameters
drop_dup: True
cols_to_drop: ['student_id', 'age', 'gender', 'bag_color', 'mode_of_transport', 'sleep_time', 'wake_time']
numerical_features: ['number_of_siblings', 'n_male', 'n_female', 'hours_per_week', 'attendance_rate', 'sleep_hours']
categorical_features: ['CCA']
binary_features: ['direct_admission', 'learning_style', 'tuition']